### ISSUE TITLE
reminders for links

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#174]
The dropdown at Home › Gsoc › Reg links  should let you "send reminder" for the checked items

**Comment by botanicvelious** [comment]
<sounak98[m]> yeah then it can take you to a page and you can select the template and send the reminders
<sounak98[m]> i guess
<botanic__> ya thatd be good
<botanic__> just a general template email page maby?
<botanic__> that we can use for a bunch of stuff
<sounak98[m]> yeah
<botanic__> like pass to the page the input data
<sounak98[m]> yeah the queryset
<sounak98[m]> and then we can select the template and then send
<botanic__> well a list of querysets
<sounak98[m]> and ofc sending will just create schedulers right?
<sounak98[m]> why list of queryset?
<botanic__> if you sending a reminder to like 10 people
<botanic__> need a queryset for each
<sounak98[m]> yeah
<botanic__> since they different emails
<sounak98[m]> oh
<botanic__> and could be different users

**Comment by APOORVA456** [comment]
PS C:\Users\Lenovo\Desktop\python-blogs-master> python manage.py runserver 0.0.0.0:8000
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x035BD468>
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\utils\autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\apps\registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37-32\filer.py", line 1
    filename='C:\Users\Lenovo\Desktop\NeuroView.datalog.txt';
            ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape




I am getting this error when I am running manage.py.What to do?
@botanicvelious

**Comment by botanicvelious** [comment]
@APOORVA456 I do not get that and I am also on windows, maby try python 64 bit?

That looks to be due to windows and linux issues with \u as that is unicide. Could also just move the code to like C:\gsoc so you dont have \U in the path

if you have problems please start a new issue 👍
