### ISSUE TITLE
recreating database throws error

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#24]
If you remove the databases and then recreate them using migrations you get errors on missing tables

```
Request Method: | GET
-- | --
http://127.0.0.1:8000/
2.1.7
OperationalError
no such table: main.auth_user
C:\Python36\lib\site-packages\django\db\backends\sqlite3\base.py in execute, line 298
C:\Python36\python.exe
3.6.8
['D:\\development\\python-blog\\python-blogs',  'C:\\Python36\\python36.zip',  'C:\\Python36\\DLLs',  'C:\\Python36\\lib',  'C:\\Python36',  'C:\\Python36\\lib\\site-packages']
Thu, 14 Feb 2019 17:33:44 -0800



Internal Server Error: /en/
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\cms\toolbar\toolbar.py", line 224, in get_user_settings
    user_settings = UserSettings.objects.select_related('clipboard').get(user=self.request.user)
  File "C:\Python36\lib\site-packages\django\db\models\query.py", line 399, in get
    self.model._meta.object_name
cms.models.settingmodels.UserSettings.DoesNotExist: UserSettings matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python36\lib\site-packages\django\db\backends\sqlite3\base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: main.auth_user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python36\lib\site-packages\django\utils\deprecation.py", line 90, in __call__
    response = self.process_request(request)
  File "C:\Python36\lib\site-packages\cms\middleware\toolbar.py", line 100, in process_request
    request.toolbar = CMSToolbar(request)
  File "C:\Python36\lib\site-packages\cms\toolbar\toolbar.py", line 129, in __init__
    self.init_toolbar(request, request_path=request_path)
  File "C:\Python36\lib\site-packages\cms\toolbar\toolbar.py", line 189, in init_toolbar
    user_settings = self.user_settings
  File "C:\Python36\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python36\lib\site-packages\cms\toolbar\toolbar.py", line 205, in user_settings
    return self.get_user_settings()
  File "C:\Python36\lib\site-packages\cms\toolbar\toolbar.py", line 230, in get_user_settings
    user=self.request.user,
  File "C:\Python36\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python36\lib\site-packages\django\db\models\query.py", line 413, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Python36\lib\site-packages\django\db\models\base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Python36\lib\site-packages\django\db\models\base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Python36\lib\site-packages\django\db\models\base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Python36\lib\site-packages\django\db\models\base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "C:\Python36\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python36\lib\site-packages\django\db\models\query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Python36\lib\site-packages\django\db\models\sql\compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python36\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 186, in execute
    return self._record(self.cursor.execute, sql, params)
  File "C:\Python36\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 124, in _record
    return method(sql, params)
  File "C:\Python36\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Python36\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Python36\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Python36\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python36\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Python36\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python36\lib\site-packages\django\db\backends\sqlite3\base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: main.auth_user
[14/Feb/2019 19:01:28] "GET /en/?edit HTTP/1.1" 500 198273
```
to reproduce 
```
rm *.db
manage.py migrate 
manage.py migrate --database auth_db
python manage.py createsuperuser  --database auth_db
manage.py runserver
```

downgrading to django 1.11.20 and changing the urls.py makes it work with runserver
```
-from django.urls import path
-path('admin/', admin.site.urls),
+url('admin/', admin.site.urls),
```
after logging in with 1.11.20 it continues to work even after a re-upgrade to 2.1.7

**Comment by sounak98** [comment]
I'll check this out.

**Comment by botanicvelious** [comment]
great! Its a bit odd how it's broken considering the database works on 2.1.7 so long as it was running on 1.11.20 at some point...

**Comment by botanicvelious** [comment]
committed a fix that works... but is less than ideal...
