### ISSUE TITLE
ADD mysql or Mariadb client to pre installation requirements 

### ISSUE THREAD

**Issue by henrykironde** [python-gsoc/python-blogs#373]
```j
Collecting mysqlclient>=1.4.4
  Using cached mysqlclient-1.4.6.tar.gz (85 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/henrykironde/python-blogs/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/rg/t6xt8whj6cx1yt3tn741j8740000gn/T/pip-install-n_9skm9s/mysqlclient/setup.py'"'"'; __file__='"'"'/private/var/folders/rg/t6xt8whj6cx1yt3tn741j8740000gn/T/pip-install-n_9skm9s/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/rg/t6xt8whj6cx1yt3tn741j8740000gn/T/pip-install-n_9skm9s/mysqlclient/pip-egg-info
         cwd: /private/var/folders/rg/t6xt8whj6cx1yt3tn741j8740000gn/T/pip-install-n_9skm9s/mysqlclient/
    Complete output (12 lines):
    /bin/sh: mysql_config: command not found
    /bin/sh: mariadb_config: command not found
    /bin/sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rg/t6xt8whj6cx1yt3tn741j8740000gn/T/pip-install-n_9skm9s/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/private/var/folders/rg/t6xt8whj6cx1yt3tn741j8740000gn/T/pip-install-n_9skm9s/mysqlclient/setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "/private/var/folders/rg/t6xt8whj6cx1yt3tn741j8740000gn/T/pip-install-n_9skm9s/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Aju100** [comment]
@henrykironde  I think now it's solved this issue. You can close this issue
