### ISSUE TITLE
GSoC 2019 - Fix Errors on user page

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#89]
When you goto the user page on the admin panel the console spits out lots of errors

```python
System check identified 32 issues (0 silenced).
March 30, 2019 - 13:44:04
Django version 2.1.7, using settings 'gsoc.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
INFO 2019-03-30 13:44:07,362 3836 1652 basehttp.py basehttp log_message 154 "GET / HTTP/1.1" 302 0
INFO 2019-03-30 13:44:07,984 3836 9140 basehttp.py basehttp log_message 154 "GET /en/ HTTP/1.1" 200 17433
INFO 2019-03-30 13:44:08,121 3836 9140 basehttp.py basehttp log_message 154 "GET /favicon.ico HTTP/1.1" 302 0
WARNING 2019-03-30 13:44:08,497 3836 2280 basehttp.py basehttp log_message 154 "GET /en/favicon.ico/ HTTP/1.1" 404 23322
INFO 2019-03-30 13:44:14,038 3836 2280 basehttp.py basehttp log_message 154 "GET /en/test-blog-1/ HTTP/1.1" 200 27378
INFO 2019-03-30 13:44:22,995 3836 2280 basehttp.py basehttp log_message 154 "POST /en/cms_login/ HTTP/1.1" 302 0
INFO 2019-03-30 13:44:23,730 3836 2280 basehttp.py basehttp log_message 154 "GET /en/ HTTP/1.1" 200 43430
INFO 2019-03-30 13:44:24,066 3836 2280 basehttp.py basehttp log_message 154 "GET /favicon.ico HTTP/1.1" 302 0
WARNING 2019-03-30 13:44:24,588 3836 15228 basehttp.py basehttp log_message 154 "GET /en/favicon.ico/ HTTP/1.1" 404 23322
INFO 2019-03-30 13:44:32,127 3836 6592 basehttp.py basehttp log_message 154 "GET /en/admin/auth/user/ HTTP/1.1" 200 17100
INFO 2019-03-30 13:44:32,136 3836 15228 basehttp.py basehttp log_message 154 "GET /en/admin/auth/user/ HTTP/1.1" 200 17100
INFO 2019-03-30 13:44:32,200 3836 6592 basehttp.py basehttp log_message 154 "GET /static/admin/css/changelists.css HTTP/1.1" 200 6170
Traceback (most recent call last):
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
ERROR 2019-03-30 13:44:32,206 3836 6592 basehttp.py basehttp log_message 154 "GET /static/admin/css/changelists.css HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 55003)
Traceback (most recent call last):
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 141, in run
    self.handle_error()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\servers\basehttp.py", line 116, in handle_error
    super().handle_error()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 368, in handle_error
    self.finish_response()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\servers\basehttp.py", line 171, in handle
    self.handle_one_request()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\servers\basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 144, in run
    self.close()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\servers\basehttp.py", line 111, in close
    super().close()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
INFO 2019-03-30 13:44:32,272 3836 15228 basehttp.py basehttp log_message 154 "GET /en/admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-03-30 13:44:32,298 3836 11252 basehttp.py basehttp log_message 154 "GET /static/admin/img/search.svg HTTP/1.1" 200 442
INFO 2019-03-30 13:44:32,298 3836 14588 basehttp.py basehttp log_message 154 "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
INFO 2019-03-30 13:44:32,376 3836 15228 basehttp.py basehttp log_message 154 "GET /en/admin/jsi18n/ HTTP/1.1" 200 3185
INFO 2019-03-30 13:44:32,411 3836 15228 basehttp.py basehttp log_message 154 "GET /static/djangocms_admin_style/img/icon_search_white@2x.png HTTP/1.1" 200 1265
Traceback (most recent call last):
INFO 2019-03-30 13:44:32,412 3836 14588 basehttp.py basehttp log_message 154 "GET /static/djangocms_admin_style/img/sorting-icons.png HTTP/1.1" 200 1447
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
INFO 2019-03-30 13:44:32,412 3836 11252 basehttp.py basehttp log_message 154 "GET /static/djangocms_admin_style/img/icon_arrow_down.png HTTP/1.1" 200 15112
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
ERROR 2019-03-30 13:44:32,420 3836 15228 basehttp.py basehttp log_message 154 "GET /static/djangocms_admin_style/img/icon_search_white@2x.png HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 55000)
Traceback (most recent call last):
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
INFO 2019-03-30 13:44:32,437 3836 11252 basehttp.py basehttp log_message 154 "GET /static/djangocms_admin_style/fonts/django-admin-iconfont.woff2?v=3.2.0 HTTP/1.1" 200 8788

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 141, in run
    self.handle_error()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\servers\basehttp.py", line 116, in handle_error
    super().handle_error()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 368, in handle_error
    self.finish_response()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\servers\basehttp.py", line 171, in handle
    self.handle_one_request()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\servers\basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\handlers.py", line 144, in run
    self.close()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\servers\basehttp.py", line 111, in close
    super().close()
  File "C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\wsgiref\simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
```

**Comment by Karna98** [comment]
I would like to work on this issue.

**Comment by Karna98** [comment]
@botanicvelious  Please elaborate the issue

**Comment by botanicvelious** [comment]
These errors show up in the console when you login and then goto the admin user page, they show up other times as well sometimes, not sure what the root cause is.

**Comment by Karna98** [comment]
@botanicvelious are you still facing same error?
Coz I'm not encountering such error

**Comment by botanicvelious** [comment]
They were semi random so ill keep an eye out.

**Comment by botanicvelious** [comment]
look to be fixed
